### ISSUE TITLE
Typo in LeafErorrMiddlewareDefaultGenerator

### ISSUE THREAD

**Issue by ragbadaskar** [brokenhandsio/leaf-error-middleware#20]
LeafErorrMiddlewareDefaultGenerator should be LeafErrorMiddlewareDefaultGenerator - it’s a minor type in spelling of “error” but trips up in the setup. The configuration will not work otherwise. Can this be fixed. Thanks.

**Comment by 0xTim** [comment]
Thanks for reporting! This is fixed in f2f7f54449d5b09a76c408587edfc2944da3a697
