### ISSUE TITLE
Allow throw Abort.redirect()

### ISSUE THREAD

**Issue by KleMiX** [brokenhandsio/leaf-error-middleware#8]
Currently when doing `throw Abort.redirect("/some-route")` is being redirected to `serverError.leaf`, many of 3xx codes are not really errors.
This middleware should allow redirect errors to pass through, since sometimes it's just easier to abort.
Since all authentication redirect functionality has been removed from vapor (can't find it in vapor 3, but google shows it was there), imagine a helper function:
```
	@discardableResult
	func checkAuth(_ req: Request) throws -> User {
		do {
			return try req.requireAuthenticated(User.self)
		}
		catch {
			throw Abort.redirect(to: "/login")
		}
	}
```

If it fails, serverError.leaf will be shown with 303 error instead of redirect.

**Comment by tonyarnold** [comment]
I've just hit this, and I agree - the anything outside of 4xx/5xx shouldn't be being intercepted by this middleware.

**Comment by 0xTim** [comment]
I agree, will add some comments to the PR
