### ISSUE TITLE
Custom 404 reason(s) passed

### ISSUE THREAD

**Issue by s3gunzel** [brokenhandsio/leaf-error-middleware#9]
I'm just wondering if it's possible to pass through a custom 404 error reason (say, "this article ID is not valid") instead of just a blank 404 error with no reason for it? 

I feel this could be an enhancement since the boilerplate already exists for server errors.

**Comment by 0xTim** [comment]
@bcousins yep I'm happy to accept PRs for a feature like that!

**Comment by s3gunzel** [comment]
@0xTim wouldn't know where to start! Sorry. Can we leave this as a feature request in case someone else with far better swift knowledge than I comes along? Thanks!

**Comment by 0xTim** [comment]
Sure!
